"""conversation turn claim

Revision ID: b2925a15defc
Revises: f676f15aff28
Create Date: 2026-09-27 13:03:05.599738
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b2925a15defc'
down_revision: str | None = 'f676f15aff28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('busy_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_conversations', 'busy_until')
    # ### end Alembic commands ###
