"""google auth and gmail

Revision ID: 63293d96de24
Revises: 4978977d9513
Create Date: 2026-09-26 19:14:39.025816
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '63293d96de24'
down_revision: str | None = '4978977d9513'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RLS_TABLES = ["mail_accounts", "email_threads", "email_messages"]  # oauth_states is global by design
TENANT_PREDICATE = "organization_id = NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('history_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='connected', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('messages_synced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mail_accounts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mail_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_accounts')),
    sa.UniqueConstraint('organization_id', 'provider', 'email_address', name=op.f('uq_mail_accounts_organization_id'))
    )
    op.create_index(op.f('ix_mail_accounts_organization_id'), 'mail_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mail_accounts_user_id'), 'mail_accounts', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_oauth_states_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state_hash', name=op.f('uq_oauth_states_state_hash'))
    )
    op.create_table('email_threads',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('contact_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('company_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], name=op.f('fk_email_threads_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_email_threads_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_threads')),
    sa.UniqueConstraint('account_id', 'provider_thread_id', name=op.f('uq_email_threads_account_id'))
    )
    op.create_index('ix_email_threads_companies', 'email_threads', ['company_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_email_threads_contacts', 'email_threads', ['contact_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_email_threads_org_recent', 'email_threads', ['organization_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_email_threads_organization_id'), 'email_threads', ['organization_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=False),
    sa.Column('rfc_message_id', sa.String(length=500), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=300), nullable=True),
    sa.Column('to', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('labels', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('has_attachments', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('contact_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('company_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], name=op.f('fk_email_messages_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_email_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], name=op.f('fk_email_messages_thread_id_email_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages')),
    sa.UniqueConstraint('account_id', 'provider_message_id', name=op.f('uq_email_messages_account_id'))
    )
    op.create_index('ix_email_messages_contacts', 'email_messages', ['contact_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_email_messages_organization_id'), 'email_messages', ['organization_id'], unique=False)
    op.create_index('ix_email_messages_thread', 'email_messages', ['thread_id', 'sent_at'], unique=False)
    op.add_column('users', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f('uq_users_google_sub'), 'users', ['google_sub'])
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
        )


def downgrade() -> None:
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_google_sub'), 'users', type_='unique')
    op.drop_column('users', 'google_sub')
    op.drop_index('ix_email_messages_thread', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_organization_id'), table_name='email_messages')
    op.drop_index('ix_email_messages_contacts', table_name='email_messages', postgresql_using='gin')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_email_threads_organization_id'), table_name='email_threads')
    op.drop_index('ix_email_threads_org_recent', table_name='email_threads')
    op.drop_index('ix_email_threads_contacts', table_name='email_threads', postgresql_using='gin')
    op.drop_index('ix_email_threads_companies', table_name='email_threads', postgresql_using='gin')
    op.drop_table('email_threads')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_mail_accounts_user_id'), table_name='mail_accounts')
    op.drop_index(op.f('ix_mail_accounts_organization_id'), table_name='mail_accounts')
    op.drop_table('mail_accounts')
    # ### end Alembic commands ###
