"""LinkedIn: page links on companies and leads, and a "linkedin" activity type.

Also moves the LinkedIn links an import kept in companies.custom_fields["LinkedIn"] into the
new column (canonical form), and gives company-named leads their company's page.
Runs as the owner role: where the owner bypasses row-level security (Neon) the data move
covers every workspace; where it doesn't, the move finds no rows and only the schema changes.

Revision ID: 9a30bbc8b00c
Revises: b2925a15defc
Create Date: 2026-09-27 15:21:50.340653
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9a30bbc8b00c'
down_revision: str | None = 'b2925a15defc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OLD_TYPES = ["call", "meeting", "email", "note", "task", "follow_up", "stage_change", "system"]
NEW_TYPES = [*OLD_TYPES, "linkedin"]
LINKEDIN_URL = r"^https?://(?:[a-z]{2,3}\.|www\.)?linkedin\.com/(company|school|showcase|in)/([^/?#]+)"


def _type_check(types: list[str]) -> None:
    # op.f(): the name is already final; don't let the naming convention prefix it again.
    op.drop_constraint(op.f("ck_activities_activity_type"), "activities", type_="check")
    op.create_check_constraint(op.f("ck_activities_activity_type"), "activities", sa.column("type").in_(types))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    _type_check(NEW_TYPES)

    # rf: the  and  below are regex back-references for Postgres, not Python escapes.
    op.execute(sa.text(rf"""
        UPDATE companies
        SET linkedin_url = regexp_replace(custom_fields ->> 'LinkedIn', '{LINKEDIN_URL}.*$',
                                          'https://www.linkedin.com/\1/\2', 'i'),
            custom_fields = custom_fields - 'LinkedIn'
        WHERE linkedin_url IS NULL AND custom_fields ->> 'LinkedIn' ~* '{LINKEDIN_URL}'
    """))
    op.execute(sa.text("""
        UPDATE leads l SET linkedin_url = c.linkedin_url
        FROM companies c
        WHERE l.organization_id = c.organization_id AND l.deleted_at IS NULL AND c.deleted_at IS NULL
          AND l.linkedin_url IS NULL AND c.linkedin_url IS NOT NULL
          AND lower(l.name) = lower(l.company_name) AND lower(l.company_name) = lower(c.name)
    """))


def downgrade() -> None:
    op.execute("DELETE FROM activities WHERE type = 'linkedin'")
    _type_check(OLD_TYPES)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'linkedin_url')
    op.drop_column('companies', 'linkedin_url')
    # ### end Alembic commands ###
