"""organization api keys

Revision ID: a835bd9b8b55
Revises: 73a26b0d8e3f
Create Date: 2026-09-27 09:55:57.594935
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a835bd9b8b55'
down_revision: str | None = '73a26b0d8e3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_PREDICATE = "organization_id = NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_api_keys',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_api_keys_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_organization_api_keys_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_api_keys')),
    sa.UniqueConstraint('organization_id', 'provider', name='uq_org_api_keys_provider')
    )
    op.create_index(op.f('ix_organization_api_keys_organization_id'), 'organization_api_keys', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE organization_api_keys ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organization_api_keys FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON organization_api_keys "
        f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON organization_api_keys")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_api_keys_organization_id'), table_name='organization_api_keys')
    op.drop_table('organization_api_keys')
    # ### end Alembic commands ###
