"""organization about

Revision ID: db703e85659c
Revises: a835bd9b8b55
Create Date: 2026-09-27 11:15:31.722866
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'db703e85659c'
down_revision: str | None = 'a835bd9b8b55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'about')
    # ### end Alembic commands ###
