"""web research

Revision ID: 843b06353a55
Revises: 63293d96de24
Create Date: 2026-09-26 19:37:43.271704
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '843b06353a55'
down_revision: str | None = '63293d96de24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RLS_TABLES = ["web_search_cache", "web_search_logs", "research_briefs"]
TENANT_PREDICATE = "organization_id = NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_briefs',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_research_briefs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_research_briefs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_briefs'))
    )
    op.create_index(op.f('ix_research_briefs_organization_id'), 'research_briefs', ['organization_id'], unique=False)
    op.create_index('ix_research_entity', 'research_briefs', ['organization_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('web_search_cache',
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_web_search_cache_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_search_cache'))
    )
    op.create_index('ix_web_cache_lookup', 'web_search_cache', ['organization_id', 'query_hash', 'created_at'], unique=False)
    op.create_index(op.f('ix_web_search_cache_organization_id'), 'web_search_cache', ['organization_id'], unique=False)
    op.create_table('web_search_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_web_search_logs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_web_search_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_search_logs'))
    )
    op.create_index('ix_web_logs_budget', 'web_search_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_web_search_logs_organization_id'), 'web_search_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
        )


def downgrade() -> None:
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_search_logs_organization_id'), table_name='web_search_logs')
    op.drop_index('ix_web_logs_budget', table_name='web_search_logs')
    op.drop_table('web_search_logs')
    op.drop_index(op.f('ix_web_search_cache_organization_id'), table_name='web_search_cache')
    op.drop_index('ix_web_cache_lookup', table_name='web_search_cache')
    op.drop_table('web_search_cache')
    op.drop_index('ix_research_entity', table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_organization_id'), table_name='research_briefs')
    op.drop_table('research_briefs')
    # ### end Alembic commands ###
