"""memory knowledge summaries jobs

Revision ID: 5510e6e5838b
Revises: bb5f5ee6cb1e
Create Date: 2026-09-26 18:32:45.207122
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5510e6e5838b'
down_revision: str | None = 'bb5f5ee6cb1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RLS_TABLES = ["ai_memories", "knowledge_chunks", "ai_conversation_summaries"]  # `jobs` is worker-only, not tenant-scoped
TENANT_PREDICATE = "organization_id = NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_dedupe', 'jobs', ['kind', 'dedupe_key'], unique=True, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_jobs_ready', 'jobs', ['run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_table('ai_conversation_summaries',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('covered_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_conversation_summaries_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_conversation_summaries_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversation_summaries')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_ai_conversation_summaries_conversation_id'))
    )
    op.create_index(op.f('ix_ai_conversation_summaries_organization_id'), 'ai_conversation_summaries', ['organization_id'], unique=False)
    op.create_table('ai_memories',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_model', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('access_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ai_memories_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_ai_memories_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_ai_memories_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_memories_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['ai_memories.id'], name=op.f('fk_ai_memories_superseded_by_id_ai_memories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_memories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_memories'))
    )
    op.create_index(op.f('ix_ai_memories_company_id'), 'ai_memories', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_memories_contact_id'), 'ai_memories', ['contact_id'], unique=False)
    op.create_index(op.f('ix_ai_memories_deal_id'), 'ai_memories', ['deal_id'], unique=False)
    op.create_index('ix_ai_memories_embedding', 'ai_memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_ai_memories_org_hash', 'ai_memories', ['organization_id', 'content_hash'], unique=False)
    op.create_index('ix_ai_memories_org_status', 'ai_memories', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_ai_memories_organization_id'), 'ai_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_memories_user_id'), 'ai_memories', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_no', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_knowledge_chunks_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_knowledge_chunks_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_knowledge_chunks_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_knowledge_chunks_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_knowledge_chunks_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index(op.f('ix_knowledge_chunks_organization_id'), 'knowledge_chunks', ['organization_id'], unique=False)
    op.create_index('ix_knowledge_embedding', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_source', 'knowledge_chunks', ['organization_id', 'source_type', 'source_id'], unique=False)
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
        )


def downgrade() -> None:
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_source', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_embedding', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_knowledge_chunks_organization_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_ai_memories_user_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_organization_id'), table_name='ai_memories')
    op.drop_index('ix_ai_memories_org_status', table_name='ai_memories')
    op.drop_index('ix_ai_memories_org_hash', table_name='ai_memories')
    op.drop_index('ix_ai_memories_embedding', table_name='ai_memories', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_ai_memories_deal_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_contact_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_company_id'), table_name='ai_memories')
    op.drop_table('ai_memories')
    op.drop_index(op.f('ix_ai_conversation_summaries_organization_id'), table_name='ai_conversation_summaries')
    op.drop_table('ai_conversation_summaries')
    op.drop_index('ix_jobs_ready', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('ix_jobs_dedupe', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('jobs')
    # ### end Alembic commands ###
