"""ai actions

Revision ID: 73a26b0d8e3f
Revises: 843b06353a55
Create Date: 2026-09-26 19:57:33.808348
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '73a26b0d8e3f'
down_revision: str | None = '843b06353a55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_PREDICATE = "organization_id = NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions',
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=10), nullable=False),
    sa.Column('tool', sa.String(length=40), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('target_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='proposed', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_actions_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_actions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_actions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_actions'))
    )
    op.create_index('ix_ai_actions_conversation', 'ai_actions', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_actions_organization_id'), 'ai_actions', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE ai_actions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ai_actions FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON ai_actions USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON ai_actions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_actions_organization_id'), table_name='ai_actions')
    op.drop_index('ix_ai_actions_conversation', table_name='ai_actions')
    op.drop_table('ai_actions')
    # ### end Alembic commands ###
